import { useState } from 'react'
import Head from 'next/head'
import Header from '../components/Header'
import Hero from '../components/Hero'
import LastCta from '../components/LastCta'
import Footer from '../components/Footer'
import About from '../components/About'
import ScrollToTop from '../components/ScrollToTop'

export default function Home() {
  const [isFromHeader, setIsFromHeader] = useState(false)
  return (
    <div className="main-page-wrapper font-gordita dark-style lg-container p0">
      <Head>
        <title>SecondBrain</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header isFromHeader={isFromHeader} setIsFromHeader={setIsFromHeader} />
      <Hero />
      <About />
      <LastCta isFromHeader={isFromHeader} />
      <Footer />
      <ScrollToTop />
    </div>
  )
}
